//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.NaNaWeb.CrossIntegrationEFGP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.nana.dsc.com/", ConfigurationName="NaNaWeb.CrossIntegrationEFGP.CrossIntegrationEFGP")]
    public interface CrossIntegrationEFGP {
        
        [System.ServiceModel.OperationContractAttribute()]
        void invokeSrv();
        
        [System.ServiceModel.OperationContractAttribute()]
        void invokeSrvAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void callbackSrv();
        
        [System.ServiceModel.OperationContractAttribute()]
        void callbackSrvAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void syncProd();
        
        [System.ServiceModel.OperationContractAttribute()]
        void syncProdAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void getDigestCode();
        
        [System.ServiceModel.OperationContractAttribute()]
        void getDigestCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void doSyncProcess();
        
        [System.ServiceModel.OperationContractAttribute()]
        void doSyncProcessAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void syncEncodingState();
        
        [System.ServiceModel.OperationContractAttribute()]
        void syncEncodingStateAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void invokeMdm();
        
        [System.ServiceModel.OperationContractAttribute()]
        void invokeMdmAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CrossIntegrationEFGPChannel : WebServiceForEFGP.NaNaWeb.CrossIntegrationEFGP.CrossIntegrationEFGP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrossIntegrationEFGPClient : System.ServiceModel.ClientBase<WebServiceForEFGP.NaNaWeb.CrossIntegrationEFGP.CrossIntegrationEFGP>, WebServiceForEFGP.NaNaWeb.CrossIntegrationEFGP.CrossIntegrationEFGP {
        
        public CrossIntegrationEFGPClient() {
        }
        
        public CrossIntegrationEFGPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrossIntegrationEFGPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrossIntegrationEFGPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrossIntegrationEFGPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void invokeSrv() {
            base.Channel.invokeSrv();
        }
        
        public void invokeSrvAsync() {
            base.Channel.invokeSrvAsync();
        }
        
        public void callbackSrv() {
            base.Channel.callbackSrv();
        }
        
        public void callbackSrvAsync() {
            base.Channel.callbackSrvAsync();
        }
        
        public void syncProd() {
            base.Channel.syncProd();
        }
        
        public void syncProdAsync() {
            base.Channel.syncProdAsync();
        }
        
        public void getDigestCode() {
            base.Channel.getDigestCode();
        }
        
        public void getDigestCodeAsync() {
            base.Channel.getDigestCodeAsync();
        }
        
        public void doSyncProcess() {
            base.Channel.doSyncProcess();
        }
        
        public void doSyncProcessAsync() {
            base.Channel.doSyncProcessAsync();
        }
        
        public void syncEncodingState() {
            base.Channel.syncEncodingState();
        }
        
        public void syncEncodingStateAsync() {
            base.Channel.syncEncodingStateAsync();
        }
        
        public void invokeMdm() {
            base.Channel.invokeMdm();
        }
        
        public void invokeMdmAsync() {
            base.Channel.invokeMdmAsync();
        }
    }
}
