//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostApplyForm_gridWithholdList
    {
        public string OID { get; set; }
        public string gd_secondNHIAmount { get; set; }
        public string gd_accountItemNo { get; set; }
        public string gd_sort { get; set; }
        public string gd_paymentItemName { get; set; }
        public string gd_originCurrency { get; set; }
        public string gd_paymentMemo { get; set; }
        public string gd_belongDepartment { get; set; }
        public string gd_paymentAmount { get; set; }
        public string gd_formatCode { get; set; }
        public string gd_Description { get; set; }
        public string gd_taxAmount { get; set; }
        public string gd_originCurrencyAmount { get; set; }
        public string gd_secondNHITaxRate { get; set; }
        public string gd_telSalesMemo { get; set; }
        public string gd_accountItem { get; set; }
        public string formSerialNumber { get; set; }
        public string gd_incomeTaxRate { get; set; }
        public string gd_NTDAmount { get; set; }
        public string gd_paymentMemoName { get; set; }
        public string gd_telSalesMemoName { get; set; }
        public string gd_withholdType { get; set; }
        public string gd_accountItemTaxRateSettingCode { get; set; }
        public string gd_paymentOriAmount { get; set; }
        public string gd_taxOriAmount { get; set; }
        public string gd_secondNHIOriAmount { get; set; }
        public string gd_oriAmount { get; set; }
    }
}
