//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostApplyForm
    {
        public string ddlNotWithhold_paymentCertificateCategory { get; set; }
        public string txtRetailId { get; set; }
        public string txtWithhold_paymentItemName { get; set; }
        public string txtWithhold_formatCode { get; set; }
        public string hidDdlCurrencySelected { get; set; }
        public string hidDdlPaymentGroupSelected { get; set; }
        public string txtNotWithhold_belongDepartmentName { get; set; }
        public string txtApplyerExtNo { get; set; }
        public string hidDdlPaymentTypeSelected { get; set; }
        public string txtIssuerDepartmentName { get; set; }
        public string hidDdlNotWithhold_paymentCertificateCategorySelected { get; set; }
        public string txtWithhold_belongDepartmentName { get; set; }
        public string txtIssuerExtNo { get; set; }
        public string SerialNumber { get; set; }
        public string txtNotWithhold_sellerTaxId { get; set; }
        public string txtApplyerName { get; set; }
        public string txtPayeeName { get; set; }
        public string txtWithhold_taxAmount { get; set; }
        public string txtWithhold_incomeTaxRate { get; set; }
        public string txtNotWithhold_paymentCertificateAmount { get; set; }
        public Nullable<System.DateTime> DateNotWithhold_paymentCertificate { get; set; }
        public string txtFormNo { get; set; }
        public string txtWithhold_belongDepartmentId { get; set; }
        public string ddlPaymentCondition { get; set; }
        public string txtWithhold_secondNHITaxRate { get; set; }
        public string btnRetailName { get; set; }
        public string ddlPaymentGroup { get; set; }
        public string txtPaymentTitle { get; set; }
        public string txtNotWithhold_formatCode { get; set; }
        public string txtWithhold_Description { get; set; }
        public string txtWithhold_telSalesMemo { get; set; }
        public string txtNotWithhold_belongDepartmentId { get; set; }
        public string txtWithhold_NTDAmount { get; set; }
        public string txtNotWithhold_statementAmount { get; set; }
        public string txtNotWithhold_telSalesMemo { get; set; }
        public string OID { get; set; }
        public string txtWithhold_accountItem { get; set; }
        public string hidDdlApplyCategorySelected { get; set; }
        public string radioIsCitizen { get; set; }
        public string txtApplyerDepartmentName { get; set; }
        public string ddlCurrency { get; set; }
        public string txtNotWithhold_paymentCertificateNo { get; set; }
        public string txtNotWithhold_taxAmount { get; set; }
        public string hidApplyManagerId { get; set; }
        public string txtIssuerDepartmentId { get; set; }
        public string txtWithhold_paymentAmount { get; set; }
        public string radioPaymentlbCertificate { get; set; }
        public string processSerialNumber { get; set; }
        public string txtWithhold_paymentMemo { get; set; }
        public string txtNotWithhold_accountItem { get; set; }
        public string ddlPaymentType { get; set; }
        public string txtIssuerId { get; set; }
        public string hidDdlPaymentConditionSelected { get; set; }
        public string txtPayeeId { get; set; }
        public string txtNotWithhold_paymentMemo { get; set; }
        public string txtNotWithhold_paymentItemName { get; set; }
        public string hidCountersignManagerId { get; set; }
        public string txtNotWithhold_statementAmountWithoutTax { get; set; }
        public string txtWithhold_originCurrencyAmount { get; set; }
        public string txtWithhold_secondNHIAmount { get; set; }
        public Nullable<double> txtCurrencyRate { get; set; }
        public string txtApplyDate { get; set; }
        public string ddlApplyCategory { get; set; }
        public string ddlWithhold_originCurrency { get; set; }
        public string txtApplyerId { get; set; }
        public string txtIssuerName { get; set; }
        public string isNeedCountersign { get; set; }
        public string txtNotWithhold_paymentCertificateWithoutTax { get; set; }
        public string txtNotWithhold_Description { get; set; }
        public string txtApplyerDepartmentId { get; set; }
        public string formSerialNumber { get; set; }
        public string txtNotWithhold_taxRate { get; set; }
        public string hidDicisionCondition { get; set; }
        public string hidHasDefaultValue { get; set; }
        public string txtWithhold_accountItemNo { get; set; }
        public string txtNotWithhold_accountItemNo { get; set; }
        public string hidIsNeedCountersign { get; set; }
        public string hidAccountingUserId { get; set; }
        public string txtNotWithhold_accountItemName { get; set; }
        public string txtWithhold_accountItemName { get; set; }
        public string txtBatchNumber { get; set; }
        public string txtWithhold_paymentMemoName { get; set; }
        public string txtNotWithhold_telSalesMemoName { get; set; }
        public string txtNotWithhold_paymentMemoName { get; set; }
        public string txtWithhold_telSalesMemoName { get; set; }
        public string hidApplyDivsion { get; set; }
        public string txtNotWithhold_sum_taxAmount { get; set; }
        public string txtNotWithhold_sum_statementAmount { get; set; }
        public string txtNotWithhold_sum_certificateAmount { get; set; }
        public string ddlWithhold_withholdType { get; set; }
        public string hidNotWithhold_accountItemTaxRateSetting_code { get; set; }
        public string hidWithhold_accountItemTaxRateSetting_code { get; set; }
        public string hidWithhold_secondNHIOriAmount { get; set; }
        public string hidWithhold_OriAmount { get; set; }
        public string hidWithhold_paymentOriAmount { get; set; }
        public string hidWithhold_taxOriAmount { get; set; }
    }
}
