//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostApplyForm_gridNotWithholdList
    {
        public string OID { get; set; }
        public string gd_accountItemNo { get; set; }
        public string gd_sort { get; set; }
        public string gd_paymentCertificateWithoutTax { get; set; }
        public string gd_paymentItemName { get; set; }
        public string gd_taxRate { get; set; }
        public string gd_statementAmountWithoutTax { get; set; }
        public string gd_paymentMemo { get; set; }
        public string gd_statementAmount { get; set; }
        public string gd_belongDepartment { get; set; }
        public string gd_paymentCertificateAmount { get; set; }
        public string gd_sellerTaxId { get; set; }
        public string gd_formatCode { get; set; }
        public string gd_Description { get; set; }
        public string gd_taxAmount { get; set; }
        public string gd_datePaymentCertificate { get; set; }
        public string gd_paymentCertificateCategory { get; set; }
        public string gd_paymentCertificateNo { get; set; }
        public string gd_telSalesMemo { get; set; }
        public string gd_accountItem { get; set; }
        public string formSerialNumber { get; set; }
        public string gd_paymentMemoName { get; set; }
        public string gd_telSalesMemoName { get; set; }
        public string gd_accountItemTaxRateSettingCode { get; set; }
    }
}
