//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NaNaEntities : DbContext
    {
        public NaNaEntities()
            : base("name=NaNaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MSG001> MSG001 { get; set; }
        public virtual DbSet<MSG001_gridMsg> MSG001_gridMsg { get; set; }
        public virtual DbSet<FormFieldsSetting> FormFieldsSetting { get; set; }
        public virtual DbSet<FormOptionsSetting> FormOptionsSetting { get; set; }
        public virtual DbSet<ViewEmployeeLightInfo> ViewEmployeeLightInfo { get; set; }
        public virtual DbSet<AccountItemTaxRateSetting> AccountItemTaxRateSetting { get; set; }
        public virtual DbSet<CostApplyForm> CostApplyForm { get; set; }
        public virtual DbSet<CostApplyForm_gridNotWithholdList> CostApplyForm_gridNotWithholdList { get; set; }
        public virtual DbSet<CostApplyForm_gridWithholdList> CostApplyForm_gridWithholdList { get; set; }
        public virtual DbSet<TempPaymentApplyForm> TempPaymentApplyForm { get; set; }
        public virtual DbSet<OutsideCostApplyForm> OutsideCostApplyForm { get; set; }
        public virtual DbSet<OutsideCostApplyForm_gdPrivateTrans> OutsideCostApplyForm_gdPrivateTrans { get; set; }
        public virtual DbSet<OutsideCostApplyForm_gdStatement> OutsideCostApplyForm_gdStatement { get; set; }
        public virtual DbSet<EmployeeTransportationSetting> EmployeeTransportationSetting { get; set; }
        public virtual DbSet<OilTransportationSubsidy> OilTransportationSubsidy { get; set; }
        public virtual DbSet<InvoiceRuleSetting> InvoiceRuleSetting { get; set; }
        public virtual DbSet<TransportationSetting> TransportationSetting { get; set; }
        public virtual DbSet<ViewEmployeeTransportationSetting> ViewEmployeeTransportationSetting { get; set; }
        public virtual DbSet<ViewERAUsersOrganizationUnitDepartment> ViewERAUsersOrganizationUnitDepartment { get; set; }
        public virtual DbSet<OrganizationUnit> OrganizationUnit { get; set; }
        public virtual DbSet<ERACategoryForInf> ERACategoryForInf { get; set; }
        public virtual DbSet<ERAPermissionForInf> ERAPermissionForInf { get; set; }
        public virtual DbSet<ViewERACategoryPermissionForInf> ViewERACategoryPermissionForInf { get; set; }
        public virtual DbSet<ERACategoryDynamicField> ERACategoryDynamicField { get; set; }
        public virtual DbSet<ERADynamicFieldSetting> ERADynamicFieldSetting { get; set; }
        public virtual DbSet<ViewERACategoryPermissionDynamicFieldSettingForInf> ViewERACategoryPermissionDynamicFieldSettingForInf { get; set; }
        public virtual DbSet<HireEmployeeForm> HireEmployeeForm { get; set; }
        public virtual DbSet<HireEmployeeForm_gdProjectAchievement> HireEmployeeForm_gdProjectAchievement { get; set; }
    }
}
