//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERAPermissionForInf
    {
        public long Id { get; set; }
        public long ERACategoryID { get; set; }
        public bool isforAll { get; set; }
        public bool enable { get; set; }
        public string departmentID { get; set; }
        public bool deleted { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
