//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormFieldsSetting
    {
        public System.Guid id { get; set; }
        public string key { get; set; }
        public string name { get; set; }
        public bool deleted { get; set; }
        public string type { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string formID { get; set; }
        public string extData1 { get; set; }
        public string extData2 { get; set; }
        public bool custOptions { get; set; }
        public bool custNotify { get; set; }
    }
}
