//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormOptionsSetting
    {
        public long id { get; set; }
        public string formName { get; set; }
        public string text { get; set; }
        public string value { get; set; }
        public string type { get; set; }
        public Nullable<int> sort { get; set; }
        public bool deleted { get; set; }
        public string fieldName { get; set; }
        public System.Guid fieldID { get; set; }
        public bool needKeyIn { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string formOID { get; set; }
        public string formNo { get; set; }
    }
}
