//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HireEmployeeForm
    {
        public string txtManageSeniorityForHR { get; set; }
        public string txtInitiativeAndResponsibilityForHumanResourcesDepartment { get; set; }
        public string rdoAbilityPotentialPeerSequence { get; set; }
        public string txtShapingSuccessfulTeamForImmediateSupervisor { get; set; }
        public string txtJobTitleForHR { get; set; }
        public string txtCourageToInnovateForImmediateSupervisor { get; set; }
        public string txtApplicantID { get; set; }
        public string txtManageSeniorityForHPDRemark { get; set; }
        public string txtTotalSeniorityForHR { get; set; }
        public string txtProblemsAndSolutionsForImmediateSupervisor { get; set; }
        public string txtProblemsAndSolutionsForHumanResourcesDepartment { get; set; }
        public string txtOtherProfessionalFunctionsForExecutives1 { get; set; }
        public string txtDateofApplication { get; set; }
        public string txtOtherProfessionalFunctionsForExecutives2 { get; set; }
        public string txtOtherProfessionalFunctionsForExecutives3 { get; set; }
        public string txtOtherProfessionalFunctionsForExecutives4 { get; set; }
        public string txtPreparerID { get; set; }
        public string txtCourageToInnovateForHumanResourcesDepartment { get; set; }
        public string txtApplicantName { get; set; }
        public string txtInitiativeAndResponsibilityForExecutives { get; set; }
        public string txtNewEmployeeName { get; set; }
        public string hidHasDefaultValue { get; set; }
        public string txtOtherProfessionalFunctionsForHR2 { get; set; }
        public string txtExcellenceForExecutives { get; set; }
        public string txtOtherProfessionalFunctionsForHR1 { get; set; }
        public string txtTotalSeniorityForHPD { get; set; }
        public string txtOtherProfessionalFunctionsForHR4 { get; set; }
        public string txtOtherProfessionalFunctionsForHR3 { get; set; }
        public string txtGoalManagementCapabilitiesForExecutives { get; set; }
        public string rdoRecruitSuccessProbabilityEstimatedForInterviewer1 { get; set; }
        public string rdoRecruitSuccessProbabilityEstimatedForInterviewer2 { get; set; }
        public string txtJobPlace { get; set; }
        public string txtManageSeniorityForHrRemark { get; set; }
        public string txtApplicantDepID { get; set; }
        public string txtGoalManagementCapabilitiesForImmediateSupervisor { get; set; }
        public string txtIdentityCategoryOther2 { get; set; }
        public string txtInterviewerName1 { get; set; }
        public string txtIdentityCategoryOther1 { get; set; }
        public string txtInterviewerName2 { get; set; }
        public string txtJobTitle { get; set; }
        public Nullable<System.DateTime> DateInterviewTimeforSupervisor { get; set; }
        public string txtShapingSuccessfulTeamForExecutives { get; set; }
        public string txtGoalManagementCapabilitiesForHumanResourcesDepartment { get; set; }
        public string processSerialNumber { get; set; }
        public string txtHonestyForHumanResourcesDepartment { get; set; }
        public string txtHonestyForExecutives { get; set; }
        public string txaPastJobsPerformanceVisits { get; set; }
        public Nullable<System.DateTime> DateInterviewTimeforExecutives { get; set; }
        public string txtRelatedSeniorityForHrRemark { get; set; }
        public string txaAdvantageforSupervisor { get; set; }
        public string txtPreparerName { get; set; }
        public string txtWorkDayShift { get; set; }
        public string txtVacanciesReason3_Name { get; set; }
        public string txtHighestEducation { get; set; }
        public string txtShapingSuccessfulTeamForHumanResourcesDepartment { get; set; }
        public string txtSalaryComparativelyForHR { get; set; }
        public string txtDailyDecisionMakingCapacityForExecutives { get; set; }
        public string txaPastJobsPerformanceVisitsForHR { get; set; }
        public string txtRelatedSeniorityForHR { get; set; }
        public string txtTotalSeniorityForHPDRemark { get; set; }
        public string txaCautionRequired2 { get; set; }
        public string txtPreparerTelephoneExtension { get; set; }
        public string txtGuidanceAndDevelopmentOfHumanResourcesForHumanResourcesDepartment { get; set; }
        public string txaCautionRequired1 { get; set; }
        public string txtRelatedSeniorityForHPDRemark { get; set; }
        public string txtApplicantExtension { get; set; }
        public string txaEnhanceSectionforExecutives { get; set; }
        public string txtSpecialSkills { get; set; }
        public string txtDevelopmentOfCommonGoalForExecutives { get; set; }
        public string SerialNumber { get; set; }
        public string txtTotalSeniorityForHrRemark { get; set; }
        public string txtProblemsAndSolutionsForExecutives { get; set; }
        public string txtInterviewerID2 { get; set; }
        public string rdoIdentityCategory1 { get; set; }
        public string txtInterviewerID1 { get; set; }
        public string rdoIdentityCategory2 { get; set; }
        public string txtDevelopmentOfCommonGoalForHumanResourcesDepartment { get; set; }
        public string txtVacancies { get; set; }
        public string txaAdvantageforExecutives { get; set; }
        public string txaAdvantageforHumanResources { get; set; }
        public string txaEnhanceSectionforSupervisor { get; set; }
        public string rdoSignoffProcessForHR { get; set; }
        public string txtExcellenceForHumanResourcesDepartment { get; set; }
        public string txtPreparerDepName { get; set; }
        public string txtInitiativeAndResponsibilityForImmediateSupervisor { get; set; }
        public string txtCommunicationAndListeningForExecutives { get; set; }
        public string txtGradeForHR { get; set; }
        public string txtOtherProfessionalFunctionsForImmediateSupervisor2 { get; set; }
        public string txtCourageToInnovateForExecutives { get; set; }
        public string txtApplicantDepName { get; set; }
        public string txtVacanciesReason2 { get; set; }
        public string txtOtherProfessionalFunctionsForImmediateSupervisor3 { get; set; }
        public string txtVacanciesReason4 { get; set; }
        public string txtOtherProfessionalFunctionsForImmediateSupervisor1 { get; set; }
        public string txtDevelopmentOfCommonGoalForImmediateSupervisor { get; set; }
        public string txtShoolDept { get; set; }
        public Nullable<System.DateTime> DateExpectedEffectiveDate { get; set; }
        public string txtDepartment { get; set; }
        public string txtOtherProfessionalFunctionsForImmediateSupervisor4 { get; set; }
        public string txtGuidanceAndDevelopmentOfHumanResourcesForExecutives { get; set; }
        public string hidDynamicSignaturePersonnel { get; set; }
        public string OID { get; set; }
        public string rdoPersonnelChangeOrResigned { get; set; }
        public string txaAdvantageforInterviewer2 { get; set; }
        public string txaAdvantageforInterviewer1 { get; set; }
        public string rdoRecruitSuccessProbabilityEstimated { get; set; }
        public string txtDailyDecisionMakingCapacityForImmediateSupervisor { get; set; }
        public string txtExcellenceForImmediateSupervisor { get; set; }
        public string txtManageSeniorityForHPD { get; set; }
        public string txtPartnershipsForExecutives { get; set; }
        public string txtOtherProfessionalFunctionsForDefinition1 { get; set; }
        public string txtOtherProfessionalFunctionsForDefinition3 { get; set; }
        public string txtOtherProfessionalFunctionsForDefinition2 { get; set; }
        public string txtOtherProfessionalFunctionsForDefinition4 { get; set; }
        public string rdoVacanciesReason4 { get; set; }
        public string txtCommunicationAndListeningForHumanResourcesDepartment { get; set; }
        public string rdoVacanciesReason2 { get; set; }
        public string rdoVacanciesReason3 { get; set; }
        public string txtDailyDecisionMakingCapacityForHumanResourcesDepartment { get; set; }
        public string rdoVacanciesReason1 { get; set; }
        public string txtApprovedSalaryForHR { get; set; }
        public string txaEnhanceSectionforHumanResources { get; set; }
        public string txtPreparerDepID { get; set; }
        public string txtOtherProfessionalFunctionsForFunction2 { get; set; }
        public string txtPartnershipsForImmediateSupervisor { get; set; }
        public string txtOtherProfessionalFunctionsForFunction1 { get; set; }
        public string txtOtherProfessionalFunctionsForFunction4 { get; set; }
        public string txtPartnershipsForHumanResourcesDepartmentTextbox10 { get; set; }
        public string txtOtherProfessionalFunctionsForFunction3 { get; set; }
        public string txtGuidanceAndDevelopmentOfHumanResourcesForImmediateSupervisor { get; set; }
        public string txaKeyObjectivesTop3 { get; set; }
        public Nullable<System.DateTime> DateInterviewTimeforHumanResources { get; set; }
        public string txtRemarkForHR { get; set; }
        public string txtHonestyForImmediateSupervisor { get; set; }
        public string txtRecommendGrade { get; set; }
        public string txtRelatedSeniorityForHPD { get; set; }
        public string txtCommunicationAndListeningForImmediateSupervisor { get; set; }
        public string formSerialNumber { get; set; }
        public string hidaddActivityEmpId { get; set; }
        public string txtPartnershipsForHumanResourcesDepartment { get; set; }
        public string hidDivisionID { get; set; }
        public string txtShool { get; set; }
        public string txtDept { get; set; }
        public string hidLevelValue { get; set; }
        public string hidReferenceLink { get; set; }
        public string hidEncryptionSalary { get; set; }
    }
}
