//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSG001_gridMsg
    {
        public string OID { get; set; }
        public string gd_segment { get; set; }
        public string gd_point_address { get; set; }
        public string gd_src { get; set; }
        public string gd_sort { get; set; }
        public string gd_type { get; set; }
        public string gd_point_id { get; set; }
        public string gd_memo { get; set; }
        public string gd_list { get; set; }
        public string gd_list_count { get; set; }
        public string gd_send_type { get; set; }
        public string gd_point_name { get; set; }
        public string gd_title { get; set; }
        public string gd_date_send { get; set; }
        public string gd_time_send { get; set; }
        public string gd_sales { get; set; }
        public string gd_point_region { get; set; }
        public string gd_condition { get; set; }
        public string gd_content { get; set; }
        public string formSerialNumber { get; set; }
    }
}
