//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSG001
    {
        public Nullable<System.DateTime> dateSendStart { get; set; }
        public string hidRadioMsgSource { get; set; }
        public string radioMsgSource { get; set; }
        public string ddlSendSystem { get; set; }
        public string txtIssuerExtNo { get; set; }
        public string SerialNumber { get; set; }
        public string txtApplyAddress { get; set; }
        public string txtMsgCount { get; set; }
        public string txtMsgMemo { get; set; }
        public string txtApplyId { get; set; }
        public string radioSendType { get; set; }
        public Nullable<System.DateTime> dateSendEnd { get; set; }
        public Nullable<System.DateTime> dateSend { get; set; }
        public string txtApplyDepId { get; set; }
        public string txtIssuerDepName { get; set; }
        public string hidRadioSendLevel { get; set; }
        public string radioMsgType { get; set; }
        public string hidDdlMsgCategory { get; set; }
        public string txtApplyName { get; set; }
        public string txtMsgContent { get; set; }
        public string chkCPDelegate { get; set; }
        public string txtApplicant { get; set; }
        public string OID { get; set; }
        public string timeSendStart { get; set; }
        public string hidRadioSendType { get; set; }
        public string txtPointName { get; set; }
        public string txtlITDelegateOther { get; set; }
        public string txtMsgTypeOther { get; set; }
        public string txtApplyExtNo { get; set; }
        public string ddlMsgCategory { get; set; }
        public string hidChbExcludeCondition { get; set; }
        public string processSerialNumber { get; set; }
        public string txtMsgTitle { get; set; }
        public string txtApplyDepart { get; set; }
        public string chbExcludeCondition { get; set; }
        public string timeSendEnd { get; set; }
        public string txtMsgCondition { get; set; }
        public string radioSendLevel { get; set; }
        public string txtIssuerId { get; set; }
        public string txtIssuerDepId { get; set; }
        public string hidRadioMsgType { get; set; }
        public string hidDateSend { get; set; }
        public string txtApplyDepName { get; set; }
        public string hidCPDelegate { get; set; }
        public string txtSendRegion { get; set; }
        public string timeSend { get; set; }
        public string txtMsgTestSendList { get; set; }
        public string txtPointID { get; set; }
        public string txtApplyDate { get; set; }
        public string hidTimeSend { get; set; }
        public string ddlITDelegateOption { get; set; }
        public string txtIssuerName { get; set; }
        public string hidIsExcludeAllCondition { get; set; }
        public string formSerialNumber { get; set; }
        public string hidApplyDivsion { get; set; }
        public string hidSendPhoneNumber { get; set; }
        public string hidITDelegateOption { get; set; }
        public string hidIsContentModify { get; set; }
        public string hidApprovedEmp { get; set; }
        public string hidOriMsgList { get; set; }
        public string hidLegalEmpGroupID { get; set; }
        public string hidSubject { get; set; }
        public string hidIsFormCreate { get; set; }
        public string hidApplyerSelectMsgCategory { get; set; }
        public string txtPreview_after { get; set; }
        public string hidApplyerCheckedBlockList { get; set; }
        public string txtPreview_before { get; set; }
    }
}
