//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationUnit
    {
        public string OID { get; set; }
        public string id { get; set; }
        public string organizationUnitName { get; set; }
        public string managerOID { get; set; }
        public string superUnitOID { get; set; }
        public int objectVersion { get; set; }
        public int organizationUnitType { get; set; }
        public string levelOID { get; set; }
        public string organizationOID { get; set; }
        public int validType { get; set; }
    }
}
