//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutsideCostApplyForm_gdPrivateTrans
    {
        public string OID { get; set; }
        public string gd_no { get; set; }
        public string gd_EtagPrice { get; set; }
        public string gd_BizTripLocationEnd { get; set; }
        public string gd_OilTransportationSubsidyPrice { get; set; }
        public string gd_EarnMileage { get; set; }
        public string gd_BizTripDescription { get; set; }
        public string gd_DateBizTrip { get; set; }
        public string gd_BizTripLocationStart { get; set; }
        public string formSerialNumber { get; set; }
        public string gd_PrivateTransportation { get; set; }
    }
}
