//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutsideCostApplyForm_gdStatement
    {
        public string OID { get; set; }
        public string gd_no { get; set; }
        public string gd_AccountItemNo { get; set; }
        public string gd_PublicTransportation { get; set; }
        public string gd_PaymentCertificateNo { get; set; }
        public string gd_PaymentCertificateWithoutTaxPrice { get; set; }
        public string gd_PaymentCertificatePrice { get; set; }
        public string gd_AccountItemName { get; set; }
        public string gd_BelongDepartmentId { get; set; }
        public string gd_PublicTaxRate { get; set; }
        public string gd_StatementAmountWithoutTax { get; set; }
        public string gd_PubicLocationStart { get; set; }
        public string gd_TransferType { get; set; }
        public string gd_PubicLocationEnd { get; set; }
        public string gd_StatementAmount { get; set; }
        public string gd_TaxPrice { get; set; }
        public string gd_PublicVATNo { get; set; }
        public string gd_BelongDepartmentName { get; set; }
        public string gd_PublicBizDescription { get; set; }
        public string gd_DatePaymentCertificate_txt { get; set; }
        public string formSerialNumber { get; set; }
        public string gd_formatCode { get; set; }
    }
}
