//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutsideCostApplyForm
    {
        public string txtPublicTrans_sumTaxAmount { get; set; }
        public string txtRetailId { get; set; }
        public string txtPublicTrans_sumStatementWithoutTaxAmount { get; set; }
        public string txtPaymentCertificatePrice { get; set; }
        public Nullable<System.DateTime> DatePaymentCertificate { get; set; }
        public string ddlPublicTransportation { get; set; }
        public string txtPublicTrans_sumPaymentCertificateWithoutTaxAmount { get; set; }
        public string txtTaxPrice { get; set; }
        public string txtApplyerExtNo { get; set; }
        public string txtIssuerDepartmentName { get; set; }
        public string txtPublicBizDescription { get; set; }
        public string txtIssuerExtNo { get; set; }
        public string hidTransferType { get; set; }
        public string SerialNumber { get; set; }
        public string txtApplyerName { get; set; }
        public string txtPayeeName { get; set; }
        public string txtBizTripLocationEnd { get; set; }
        public string txtBatchNumber { get; set; }
        public string hidPrivateTransportation { get; set; }
        public string hidPaymentCondition { get; set; }
        public string txtPubicLocationEnd { get; set; }
        public string txtPaymentCertificateWithoutTaxPrice { get; set; }
        public string radioPrivateTrans_subsidyLimit { get; set; }
        public string txtAccountItemName { get; set; }
        public string hidDicisionCondition { get; set; }
        public string txtPubicLocationStart { get; set; }
        public string txtPrivateTrans_sumStatementAmount { get; set; }
        public string txtPaymentCertificateNo { get; set; }
        public string txtPrivateTrans_subsidyLimitAmount { get; set; }
        public string txtPublicVATNo { get; set; }
        public string hidPublicTransportation { get; set; }
        public string hidPaymentType { get; set; }
        public string txtPaymentTitle { get; set; }
        public string radioPrivateTrans_earnMileageSubsidy { get; set; }
        public string txtTotalAmount_etagPrice { get; set; }
        public string hidPaymentGroup { get; set; }
        public string hidHasDefaultValue { get; set; }
        public string txtBelongDepartmentId { get; set; }
        public string txtAccountItemNo { get; set; }
        public string txtBelongDepartmentName { get; set; }
        public string txtPublicTrans_sumStatementAmount { get; set; }
        public string radioTransferType { get; set; }
        public string OID { get; set; }
        public string hidDdlApplyCategorySelected { get; set; }
        public string txtPrivateTrans_sumStatementWithoutAmount { get; set; }
        public string txtApplyerDepartmentName { get; set; }
        public Nullable<System.DateTime> DateBizTrip { get; set; }
        public string ddlPrivateTransportation { get; set; }
        public string txtTotalAmount_oilTransportationSubsidyPrice { get; set; }
        public string txtBizTripLocationStart { get; set; }
        public string txtPublicTrans_sumPaymentCertificateAmount { get; set; }
        public string txtBizTripDescription { get; set; }
        public string txtIssuerDepartmentId { get; set; }
        public string txtStatementAmountWithoutTax { get; set; }
        public string txtRetailName { get; set; }
        public string processSerialNumber { get; set; }
        public string txtIssuerId { get; set; }
        public string txtPublicTaxRate { get; set; }
        public string txtStatementAmount { get; set; }
        public string txtPayeeId { get; set; }
        public string hidCountersignManagerId { get; set; }
        public string txtOilTransportationSubsidyPrice { get; set; }
        public string hidApplyDivsion { get; set; }
        public string txtEtagPrice { get; set; }
        public string txtApplyDate { get; set; }
        public string hidAccountingUserId { get; set; }
        public string ddlApplyCategory { get; set; }
        public string txtApplyerId { get; set; }
        public string txtPrivateTrans_earnMileageSubsidyAmount { get; set; }
        public string txtIssuerName { get; set; }
        public string hidIsNeedCountersign { get; set; }
        public string txtEarnMileage { get; set; }
        public string txtApplyerDepartmentId { get; set; }
        public string formSerialNumber { get; set; }
        public string txtSumTotalPrice { get; set; }
        public string txtPrivateTrans_sumETagPrice { get; set; }
        public string txtPrivateTrans_sumPaymentCertificatePrice { get; set; }
        public string txtVATNo { get; set; }
        public string txtPrivateTrans_sumTaxPrice { get; set; }
        public string hidFormatCode { get; set; }
    }
}
