//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempPaymentApplyForm
    {
        public string OID { get; set; }
        public string txtDescription { get; set; }
        public Nullable<double> hidInterimPaymentAmount { get; set; }
        public string txtApplyUnitHandlingId { get; set; }
        public string txtApplyerDepartmentName { get; set; }
        public string txtApplyerExtNo { get; set; }
        public string txtIssuerDepartmentName { get; set; }
        public string txtIssuerExtNo { get; set; }
        public string radioPaymentType { get; set; }
        public string SerialNumber { get; set; }
        public string txtApplyerName { get; set; }
        public string txtBatchNumber { get; set; }
        public string txtRecipient { get; set; }
        public string txtIssuerDepartmentId { get; set; }
        public string txtApplyUnitHandlingName { get; set; }
        public string processSerialNumber { get; set; }
        public string txtBankBranchName { get; set; }
        public string hidDicisionCondition { get; set; }
        public string txtIssuerId { get; set; }
        public string hidAccountEmpNo { get; set; }
        public string txtBankName { get; set; }
        public string txtInterimPaymentAmount { get; set; }
        public string hidHasDefaultValue { get; set; }
        public string txtApplyDate { get; set; }
        public string txtApplyerId { get; set; }
        public Nullable<System.DateTime> DateRequire { get; set; }
        public string txtIssuerName { get; set; }
        public string txtBankAccountNo { get; set; }
        public string txtApplyerDepartmentId { get; set; }
        public string formSerialNumber { get; set; }
        public string hidPaymentCondition { get; set; }
        public string hidPaymentGroup { get; set; }
    }
}
