//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmployeeLightInfo
    {
        public string ID { get; set; }
        public string userName { get; set; }
        public string phoneNumber { get; set; }
        public string ldapid { get; set; }
        public string departmentName { get; set; }
        public string departmentID { get; set; }
        public string employeeOID { get; set; }
        public string userOID { get; set; }
        public string Expr1 { get; set; }
    }
}
