//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForEFGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewERAUsersOrganizationUnitDepartment
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string OUID { get; set; }
        public string OUName { get; set; }
    }
}
